"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let places = [`usa`, `canada`, `saudiarabia`, `turkey`, `malasia`];
//console.log(`original:`+places);
//console.log(`copy ` +[...places].sort ());
//console.log(`original:`+places);
console.log(`copy ` + [...places].sort().reverse());
console.log(`copy ` + [...places].sort().reverse());
console.log(`original:` + places.sort());
console.log(`copy ` + [...places].sort().reverse());
